
version: '3.8'
services:
  webapi:
    build:
      context: ./WebAppWithDocker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  webclient:
    build:
      context: ./webclient
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapi
      - webclient
